#ifndef PROTOCOL_H
#define PROTOCOL_H

#define PORT 8080

#define GRADUATED_USERS_OPTION 1
#define SKILLS_FROM_CITY_OPTION 2
#define NEW_EXPERIENCE_OPTION 3
#define PROFILE_EXPERIENCE_OPTION 4
#define ALL_PROFILE_OPTION 5
#define PROFILE_ALL_INFO_OPTION 6
#define EXIT_OPTION 7

#define MIN_OPTION 1
#define MAX_OPTION 7

#define SMALL_MESSAGE 300
#define BIG_MESSAGE 1300

#endif